apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: {APP_NAME}
    version: "{APP_VERSION}"
  name: {APP_NAME}
  namespace: {NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {APP_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {APP_NAME}
        version: "{APP_VERSION}"
    spec:
      containers:
      - image: {REGISTRY_DOCKER}/{APP_NAME}:{APP_VERSION}
        imagePullPolicy: Always
        name: {APP_NAME}
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
