apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: {APP_NAME}
  namespace: {NAMESPACE}
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {APP_NAME}
  targetCPUUtilizationPercentage: 50

