apiVersion: v1
kind: Service
metadata:
  labels:
    run: {APP_NAME}
  name: {APP_NAME}
  namespace: {NAMESPACE}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: {APP_NAME}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
